name: Bug
description: Report a bug.
title: "bug: "
labels: ["type:bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: "1) ...\n2) ..."
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant output from logs/events.jsonl (redact secrets).
  - type: input
    id: version
    attributes:
      label: Commit / version
      description: git commit hash or release tag
